---
application:
  name: "netart"
  project: "net art"
  organization: "AUSTIN FRANKLIN MUSIC"
  publicly_accessible: "true"
routers:
- name: "main-netart"
  routes:
  - application_name: "netart"
    paths:
    - "/*"
